AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Cognito UserPool Federation CloudFormation Support"

Parameters:
  Environment:
    Description: "Environment"
    Type: "String"
    Default: "dev"

  CodeUri:
    Description: "Code Uri Path"
    Type: "String"

  FunctionName:
    Description: "The Function name"
    Type: "String"

Resources:
  Lambda:
    Type: "AWS::Serverless::Function"
    DependsOn:
      - "Role"
      - "LogGroup"
    Properties:
      FunctionName: !Sub "${FunctionName}-${AWS::Region}-${Environment}"
      Description: !Sub "${FunctionName}-${AWS::Region}-${Environment}"
      Role: !GetAtt "Role.Arn"
      Handler: "handler"
      Runtime: "go1.x"
      CodeUri: !Ref "CodeUri"
      Environment:
        Variables:
          ENVIRONMENT: !Ref "Environment"
      Timeout: 60
      MemorySize: 128

  Role:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${FunctionName}-role-${AWS::Region}-${Environment}"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "lambda.amazonaws.com"
      Policies:
        - PolicyName: !Sub "${FunctionName}-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cognito-idp:UpdateUserPoolClient"
                  - "cognito-idp:DescribeIdentityProvider"
                  - "cognito-idp:UpdateIdentityProvider"
                  - "cognito-idp:CreateIdentityProvider"
                  - "cognito-idp:DeleteIdentityProvider"
                Resource: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*"

  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FunctionName}-${AWS::Region}-${Environment}"
      RetentionInDays: 90
